### ISSUE TITLE
Interactive show

### ISSUE THREAD

**Issue by pfebrer** [chriscave/mpl_ascii#4]
Is it possible to make `figure.show()` work with this backend? I have no idea how difficult it is.

Right now if I try it I get:

```
UserWarning: FigureCanvasAscii is non-interactive, and thus cannot be shown
```

**Comment by chriscave** [comment]
Let me take a look at it. I can't imagine it being too tricky to get it working. 

Thanks for the feature request!

**Comment by chriscave** [comment]
@pfebrer so I think it would be really helpful if you could elaborate a bit more on this feature request. Here's a few of questions that might help me understand it a bit better:
- What do you expect should happen when you use figure.show() with ascii plots?
- Should this be run in an ipython / jupyter notebook environment?
- Can you provide a minimal example that captures what you would like to see?

Thanks!

**Comment by pfebrer** [comment]
Yes, sorry. I expect this to work on a notebook, where the plot should show on the cell's output.

**Comment by chriscave** [comment]
Hey no worries, I'm really pleased you're making feature requests.

So as I understand it, this for displaying the ascii plot in a cell in a jupyter notebook. I have a couple of follow up questions:
- As I understand it (but please correct me if I'm wrong :) ) Figure.show() is usually used for allowing interactivity for the user in a notebook environment, like in this [example](https://matplotlib.org/stable/gallery/widgets/polygon_selector_simple.html#). However this request is not about using interactivity, but to display the figure in the cell without any interactivity. Did I understand correctly?
- If that is the case then why use figure.show() and not plt.show() which does display in a cell.
- Can explain the situation you find yourself in when you want to use ascii plots in a jupyter notebook and not just use regular matplotlib without the ascii backend.

**Comment by pfebrer** [comment]
Hmm that's true `Figure.show` is intended for interactivity. However I use it to show a particular figure, because `plt.show` shows all figures and as far as I know there's no way of just showing one of them (which is very weird).

**Comment by chriscave** [comment]
That's a fair point. If all you need is to display a particular figure then I think this should be pretty doable.

On the interactivity side of things, I don't think I see a good use case yet to warrant making ascii plots interactive. However I'm definitely open to being convinced otherwise :)

**Comment by pfebrer** [comment]
Yeah I don't see any need for interactivity either :)
