### ISSUE TITLE
Control global variables through environment variables.

### ISSUE THREAD

**Issue by pfebrer** [chriscave/mpl_ascii#7]
I'm seeing how the backend plays with our plotting CLI, and one thing that would be cool is to be able to tweak the global variables through environment variables, so that you don't need to actually change your python code to get different size for the axes.

Maybe the env variable could be the default, which could be overwritten by setting the variables in python.

**Comment by chriscave** [comment]
Hey sorry for taking some time to reply.

I think that's a great idea. So just to make sure I understand. If there are environment variables, say for example MPL_ASCII_AXES_HEIGHT and MPL_ASCII_AXES_WIDTH, then the library should read the height and width from them unless it has been overwritten inside python program.

**Comment by pfebrer** [comment]
Yes, that's what I mean 👍 I guess it could work with enabling colors too

**Comment by chriscave** [comment]
@pfebrer did you get a chance to check out the PR I made on this? I would really appreciate any comments or suggestions you have on this.
